### ISSUE TITLE
How to integrate this library with `ngx-build-plus`?

### ISSUE THREAD

**Issue by liuxinqiong** [JLHwung/webpack-dll-ng-module-loader#151]
Can you tell me how to  bundling vendor to webpack dll in angular7?

I can't eject the config of webpack!

Thanks!

**Comment by JLHwung** [comment]
Hi Xinqiong,

Thanks for your issues. Could you prepare a minimal reproduction repository for your question? The reproduction repository will help

- Knowing your project architecture. i.e. Is that a seed project bootstrapped by Angular CLI? Or other angular-project starter?

- Identifying the motivation of using this library. As is said on the project README

> If you are not bundling @angular/core to webpack dll, you probably never need this plugin.

A repository demonstrating that it is using Webpack dll config would definitely finds this library a handy tool. If you are considering about using Webpack dll on your project, here is the [usage](https://webpack.js.org/plugins/dll-plugin/#usage) of webpack dll.


> I can't eject the config of webpack!

I assume you refers to `ng eject` usage of the Angular CLI. According to [this thread](https://github.com/angular/angular-cli/issues/10618#issuecomment-425506339), the `ng eject` has been disabled since Angular 6. 

There is an alternative solution called [ngx-builder-plus](https://github.com/manfredsteyer/ngx-build-plus), if you would like to give a try, here is a [thread](https://github.com/JLHwung/webpack-dll-ng-module-loader/issues/44#issuecomment-452975634) that might help you.

**Comment by liuxinqiong** [comment]
@JLHwung Thanks for your reply！

My project is created by Angular CLI. Because the project need a lot of dependence, the build time need 3-6min, it's too long.

So I want to use DllPlugin to optimize the build speed. But it didn't go well。Just as you say, the ng eject has been disabled since Angular 6.

With your reply, here is my conclusion, is it right?
* use ngx-builder-plus to extend wabpack config
* use this loader to enable dll-plugin in angular when I am bundling @angular/core to webpack dll

**Comment by liuxinqiong** [comment]
I find not only ` @angular/core`  will cause lazy loaded routes not build in. Maybe any of the `@angular/xxx` both have the problem。

**Comment by liuxinqiong** [comment]
Hi @JLHwung 

I try it with your example，But when I add AngularCompilerPlugin in my webpack.config.js. It throws a error as below

> An @ngtools/webpack plugin already exist for this compilation.

Here is my [repository ](https://github.com/liuxinqiong/angular-use-dll-plugin), Thanks a lot!

**Comment by JLHwung** [comment]
Hi Xinqiong,

I've checked out your repository. As I mentioned before on [this thread](https://github.com/JLHwung/webpack-dll-ng-module-loader/issues/44#issuecomment-452975634), the `ngx-build-plus` uses `webpack-merge` to merge the extra webpack config into the builtin webpack config from `@angular-devkit/build-angular`. The builtin webpack config has already [included](https://github.com/angular/angular-cli/blob/v8.0.0-rc.4/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/typescript.ts#L130) an instance of `@ngtools/webpack` plugin. So the what happens on your repository is:

The `webpack-merge` merges your extra configuration
```
{
  plugins: [
    new CheatAngularCompilerResourcePlugin(/* arguments */),
    new AngularCompilerPlugin(/* arguments */),
  ]
}
```
with the built-in configuration
```
{
  plugins: [
    new AngularCompilerPlugin(/* arguments */),
  ]
}
```

to this implicit actual configuration
```
{
  plugins: [
    new AngularCompilerPlugin(/* arguments */),
    new CheatAngularCompilerResourcePlugin(/* arguments */),
    new AngularCompilerPlugin(/* arguments */),
  ]
}
```

As you can see there is two instance of `AngularCompilerPlugin`, so it throws an error

> An @ngtools/webpack plugin already exist for this compilation.

At first glance we may wonder if it works by removing the `new AngularCompilerPlugin(/* arguments */)` from the extra webpack configuration. However, it does not work since `CheatAngularCompilerResourcePlugin` must come before `new AngularCompilerPlugin`. Therefore the issue here is identical to #44.

Fortunately since then `ngx-build-plus` has kindly [offered a way](https://github.com/manfredsteyer/ngx-build-plus#using-different-merging-strategies) to customize how the extra webpack config should merge with the builtin webpack configuration.

I will give it a try today and let you know if it works. It is not a big effort so stay tuned.

**Comment by JLHwung** [comment]
Hi Xinqiong,

1.2.0 has been published and [here](https://github.com/JLHwung/webpack-dll-ng-module-loader/blob/master/integration/ngx-build-plus/README.md) is a step-by-step guide to integrate with `ngx-build-plus`. Feel free to reply should you have further questions.

**Comment by liuxinqiong** [comment]
Hi @JLHwung,

I have a try  today. Nice! Perfect! Wonderful! Thanks.

As I saw this words below:

> we manually add it to the script tag of your src/index.html

I found that I had misunderstanding about the dllPlugin before.

Before I thought the dllPlugin's function is pre-build vendor package. When I need build, the webpack will use dllReferencePlugin to find the built source, and then package it into a new bundle. But now I think it's wrong. the webpack won't build it into a new bundle, just not re-build it. So we have to manually add it to index.html or use another plugin to help automatically. is it right?

Do you have any way to see the full webpack config? When I know the ngx-build-plus  use webpack-merge plugin to merge the config,  and support different strategies. I have a new idea to do more, Such as use happypack？

**Comment by JLHwung** [comment]
> So we have to manually add it to index.html or use another plugin to help automatically. is it right?

Absolutely. During every compilation, the dllReferencePlugin will utilize the manifest.json to determine if the module the has requested is a dllModule, so webpack don’t have to bring the source and will delegate the module to a dllModule request.

So the dll.js is part of the whole application bundle. Think of the dll files in the Windows application, the concept borrows from here.

In case of the whole webpack config. I am not an expert on ng-build-plus. If I were you, I will set debugger on the merge step and run the build command with inspect. You can dump the whole configuration from the v8inspector.

Sure you can go ahead for happypack. With an partial webpack config, you can do whatever you like.

**Comment by liuxinqiong** [comment]
> > So we have to manually add it to index.html or use another plugin to help automatically. is it right?
> 
> Absolutely. During every compilation, the dllReferencePlugin will utilize the manifest.json to determine if the module the user has requested is a dllModule or not. If it is, webpack won’t have to bring the source of module in and will instead delegate the module to a dllModule request.
> 
> So the dll.js is part of the whole application bundle. Think of the dll files in the Windows application, the concept borrows from here.
> 
> In case of the whole webpack config. I am not an expert on ng-build-plus. If I were you, I will set debugger on the merge step and run the build command with inspect. You can dump the whole configuration from the v8inspector.
> 
> Sure you can go ahead for happypack. With an partial webpack config, you can do whatever you like.

Get it! Thanks!
